"""add all models

Revision ID: d6a8c54ed761
Revises: 
Create Date: 2024-04-17 20:55:06.690510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6a8c54ed761"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("refresh_token", sa.UUID(), nullable=False),
        sa.Column("ua", sa.String(length=200), nullable=False),
        sa.Column("ip", sa.String(length=15), nullable=False),
        sa.Column("expires_in", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "clients",
        sa.Column("account_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("surname", sa.String(length=32), nullable=False),
        sa.Column("second_name", sa.String(length=32), nullable=False),
        sa.Column("birthday", sa.DateTime(), nullable=False),
        sa.Column("TIN", sa.String(length=12), nullable=False),
        sa.Column("responsible_person_full_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="Не в работе", nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("TIN"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clients")
    op.drop_table("users")
    op.drop_table("tokens")
    # ### end Alembic commands ###
